name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release BetterWho.csproj

      - name: Prepare artifacts
        run: |
          mkdir -p addons/counterstrikesharp/plugins/BetterWho
          mkdir -p addons/counterstrikesharp/configs/plugins/BetterWho
          cp bin/Release/net8.0/BetterWho.dll addons/counterstrikesharp/plugins/BetterWho/BetterWho.dll
          if [ -f configs/BetterWho.json ]; then
            cp configs/BetterWho.json addons/counterstrikesharp/configs/plugins/BetterWho/BetterWho.json
          fi

      - name: Package addon
        run: zip -r BetterWho.zip addons/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BetterWho
          path: addons/

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: BetterWho.zip
